from .comfyui import DEFAULT_CFG, DEFAULT_STEPS

# Default generation parameters used when initializing a new CSV
DEFAULT_MODEL = "gpt-oss:20b"
DEFAULT_TEMPERATURE = 0.8
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TOP_P = 0.95
DEFAULT_SEED = 31337
DEFAULT_WIDTH = 1024
DEFAULT_HEIGHT = 1024
DEFAULT_FPS = 24
DEFAULT_VIDEO_LENGTH = 3
DEFAULT_TIMEOUT = 300

# Video CSV schema
VIDEO_COLUMNS = [
    "selected",
    "id",
    "title",
    "synopsis",
    "llm_model",
    "checkpoint",
    "comfy_vae",
    "comfy_lora",
    "temperature",
    "max_tokens",
    "top_p",
    "cfg",
    "steps",
    "seed",
    "batch_count",
    "width",
    "height",
    "story_prompt",
    "bgm_prompt",
    "taste_prompt",
    "character_voice",
    "movie_prompt",
    "video_length",
    "fps",
    "status",
    "needs_approve",
    "controlnet_image",
]

VIDEO_DEFAULTS = {
    "selected": False,
    "id": "",
    "title": "",
    "synopsis": "",
    "llm_model": DEFAULT_MODEL,
    "checkpoint": "",
    "comfy_vae": "",
    "comfy_lora": "",
    "temperature": DEFAULT_TEMPERATURE,
    "max_tokens": DEFAULT_MAX_TOKENS,
    "top_p": DEFAULT_TOP_P,
    "cfg": DEFAULT_CFG,
    "steps": DEFAULT_STEPS,
    "seed": DEFAULT_SEED,
    "batch_count": 1,
    "width": DEFAULT_WIDTH,
    "height": DEFAULT_HEIGHT,
    "story_prompt": "",
    "bgm_prompt": "",
    "taste_prompt": "",
    "character_voice": "",
    "movie_prompt": "",
    "video_length": DEFAULT_VIDEO_LENGTH,
    "fps": DEFAULT_FPS,
    "status": "",
    "needs_approve": "",
    "controlnet_image": "",
}

# Image CSV schema
IMAGE_COLUMNS = [
    "selected",
    "id",
    "category",
    "tags",
    "nsfw",
    "ja_prompt",
    "llm_model",
    "llm_environment",
    "image_prompt",
    "alt_text",
    "slug",
    "excerpt",
    "canonical_url",
    "meta_keywords",
    "json_ld",
    "negative_prompt",
    "sfw_negative_prompt",
    "image_path",
    "post_url",
    "post_site",
    "post_id",
    "wordpress_site",
    "wordpress_account",
    "views_yesterday",
    "views_week",
    "views_month",
    "checkpoint",
    "comfy_vae",
    "comfy_lora",
    "temperature",
    "max_tokens",
    "top_p",
    "cfg",
    "steps",
    "seed",
    "batch_count",
    "width",
    "height",
    "timeout",
]

IMAGE_DEFAULTS = {
    "selected": False,
    "id": "",
    "category": "",
    "tags": "",
    "nsfw": False,
    "ja_prompt": "",
    "llm_model": DEFAULT_MODEL,
    "llm_environment": "Ollama",
    "image_prompt": "",
    "alt_text": "",
    "slug": "",
    "excerpt": "",
    "canonical_url": "",
    "meta_keywords": "",
    "json_ld": "",
    "negative_prompt": "",
    "sfw_negative_prompt": "",
    "image_path": "",
    "post_url": "",
    "post_site": "",
    "post_id": "",
    "wordpress_site": "",
    "wordpress_account": "",
    "views_yesterday": 0,
    "views_week": 0,
    "views_month": 0,
    "checkpoint": "",
    "comfy_vae": "",
    "comfy_lora": "",
    "temperature": DEFAULT_TEMPERATURE,
    "max_tokens": DEFAULT_MAX_TOKENS,
    "top_p": DEFAULT_TOP_P,
    "cfg": DEFAULT_CFG,
    "steps": DEFAULT_STEPS,
    "seed": DEFAULT_SEED,
    "batch_count": 1,
    "width": DEFAULT_WIDTH,
    "height": DEFAULT_HEIGHT,
    "timeout": DEFAULT_TIMEOUT,
}
